### ISSUE TITLE
Replace Docker ENV for Username and Password

### ISSUE THREAD

**Issue by nehayward** [quintilesims/layer0#529] opened 2018-01-29 22:33 UTC
A CI bot needs to be created with the carbon shared emailed and then the env variables in the travis config need to be replaced [here](https://travis-ci.org/quintilesims/layer0/settings)

**Comment by diemonster** [comment] 2018-03-22 17:00
Closing this, the purpose and objective of the issue is too ambiguous.

**Closed by diemonster** 2018-03-22 17:00 UTC
