### ISSUE TITLE
Documentation references repo that has not been migrated to github

### ISSUE THREAD

**Issue by Cryowatt** [quintilesims/layer0#138] opened 2017-03-20 16:32 UTC
https://quintilesims.github.io/layer0/guides/consul/#before-you-start references https://github.com/quintilesims/consul-local/blob/master/consul.json which has not been migrated.

**Comment by diemonster** [comment] 2017-03-20 16:40
duplicate of https://github.com/quintilesims/layer0/issues/112

**Closed by diemonster** 2017-03-20 16:40 UTC
