### ISSUE TITLE
failure to delete env when environment_link is used

### ISSUE THREAD

**Issue by davemeyer** [quintilesims/layer0#538] opened 2018-02-02 19:38 UTC
### Expected behavior

an environment that has been linked via `layer0_environment_link` should handle deletion of the link at destruction time.

### Actual behavior

the link is not deleted and the environment fails to be destroyed.

### Steps to reproduce the behavior

1.  create environment A using state A
2.  create environment B using state B
3.  link env A and env B using state B
4.  destroy env A. destruction times out when deleting security groups

Please also include the following if applicable:

this happens with l0 v0.10.5
this does not happen with l0 v0.10.3

**Comment by jparsons04** [comment] 2018-02-05 20:19
I created a new l0 instance based on v0.10.5 and followed the reproducing steps. Here are the results of my manual testing: https://gist.github.com/jparsons04/1c5b8331aa4246aa3ee772bfd6b48e0c

I also found in the v0.10.5 logic that suggests that Environment links are deleted as part of the Delete Dependencies step.
See: 
https://github.com/quintilesims/layer0/blob/v0.10.5/runner/job/environment.go#L28
https://github.com/quintilesims/layer0/blob/v0.10.5/api/logic/environment_logic.go#L52

The behavior and the code suggest that the links are being discovered and deleted as part of the delete environment process.

Can you confirm that this is still an issue for you on v0.10.5?

**Comment by davemeyer** [comment] 2018-02-08 02:06
i think that my repro example may have been too simplified and may have hidden the actual issue, because i can still repro this in our deployment. the more complete scenario is this:
environments:
- haproxyA
- haproxyB
- envA
- envB
link creation:
1.  env A -> haproxyA
2. envA -> haproxyB
3. envB -> haproxyA
4. envB -> haproxyB
then attempt to delete envA
it looks like the fact that envA is linked to multiple environments is the problem here. when i look at the security groups for envA, i see that one of the two links has been destroyed. but the other linked SG is still there. so i'm guessing that there is some assumption that an env will only be linked to one other env?

**Comment by jparsons04** [comment] 2018-02-10 00:43
In my research, I have found that with v0.10.5+, links are getting overwritten. The ingress rules for the security groups are correctly being created when the links are being created, however, in the tags database, the `link` key value pairs are getting overwritten.

So, in your example. envA -> haproxyA is linking as normal. But as soon as you link envA -> haproxyB, the tags database thinks that the only link that exists from envA is to haproxyB. The ingress rules for envA though reference both haproxyA and haproxyB. So when you go to delete envA you can't delete the security group because the ingress rule for haproxyA is orphened.

We are going to discuss this issue in more detail next week on how to proceed, but I'm relatively confident this is the reason you are seeing what you are seeing.

**Comment by jparsons04** [comment] 2018-02-26 20:25
After discussing this further, I understand that this issue is resolved in a branch that will be included into the v0.11.0 release. We fundamentally changed how environment linking is done.

So, I'm going to mark this as Won't Fix, but if this issue surfaces again after the v0.11.0, we'll reopen the issue.

**Closed** 2018-02-26 20:26 UTC
Labels: bug
