### ISSUE TITLE
Consul Task Definition Links 404

### ISSUE THREAD

**Issue by tlake** [quintilesims/layer0#141] opened 2017-03-20 22:43 UTC
The Consul and Consul-with-Guestbook guides have links to consul task definitions that 404.

(Is https://github.com/quintilesims/consul/blob/master/consul-master.json what we're looking for there?)

**Comment by diemonster** [comment] 2017-03-21 17:05
duplicate of https://github.com/quintilesims/layer0/issues/112

**Closed by diemonster** 2017-03-21 17:05 UTC
Labels: Doc
