### ISSUE TITLE
Default listener/default health check is created when creating a load balancer

### ISSUE THREAD

**Issue by jparsons04** [quintilesims/layer0#412] opened 2017-11-02 23:33 UTC
### Expected behavior
Should a default port/default health check be created by default or should a request be required to provide a health check and at least one port?

### Actual behavior
When creating load balancers, if no ports are specified in the request, a default listener is created (TCP port 80 -> TCP port 80) and a health check is created also on TCP:80.

**Comment by jparsons04** [comment] 2017-11-02 23:33
Spawned from this comment: https://github.com/quintilesims/layer0/pull/410#discussion_r148648378

**Comment by tribaljack** [comment] 2017-11-08 21:45
Should have consolidated single place of entry for defaults for v0.11.0; behavior can change after.

**Comment by diemonster** [comment] 2018-03-22 17:08
Closing, the behavior called out is/was intended.

**Closed by diemonster** 2018-03-22 17:08 UTC
