### ISSUE TITLE
Loadbalancer created in invalid state if you specify an invalid --healthcheck-target

### ISSUE THREAD

**Issue by Cryowatt** [quintilesims/layer0#143] opened 2017-03-21 17:37 UTC
Repro:
```
>l0 loadbalancer create --private --port 8500:8500/http --healthcheck-target HTTP:8500 env lbname
```

Results in the error 
```
AWS Error: healthcheck http target must specify a port followed by a path that begins with a slash. e.g. http:80/ping/this/path (code 'ValidationError')
```

If I check the loadbalancer list, I end up with something like this:
```
>l0 loadbalancer list
LOADBALANCER ID  LOADBALANCER NAME  ENVIRONMENT
api              api                api
lbname55c41
```

But I can't delete it with L0
```
>l0 loadbalancer delete lbname55c41
Load Balancer lookup using 'lbname55c41' yielded no matches.
```

**Comment by diemonster** [comment] 2017-03-21 17:40
duplicate of https://github.com/quintilesims/layer0/issues/119

**Closed by diemonster** 2017-03-21 17:40 UTC
